### ISSUE TITLE
Python 3.x support (ImportError: No module named 'StringIO')

### ISSUE THREAD

**Issue by 0xdevalias** [nahamsec/JSParser#18]
When running `python handler.py` I get the following error:

```
ImportError: No module named 'StringIO'
```

I believe this is related to python 3.x

```
⇒  python --version
Python 3.5.2
```

**Comment by gopinath6** [comment]
May i know any fix available for this?

**Comment by EdOverflow** [comment]
Use the following:

```python
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
```

**Comment by gopinath6** [comment]
Thanks.After above fix  got below error

![image](https://user-images.githubusercontent.com/6551119/36373301-b7d38a80-158d-11e8-8794-d1f465a85ba6.png)

**Comment by EdOverflow** [comment]
`urlparse` was renamed to `urllib.parse` in Python 3.

**Comment by gopinath6** [comment]
@EdOverflow Thanks a lot . it worked.

**Comment by Sechunt3r** [comment]
When running python3 handler.py I get the following error:

ModuleNotFoundError: No module named 'StringIO'

I already added this following code in my handler.py and also i changed the urlparse to urllib.parse!

Thanks for advance @EdOverflow

**Comment by EdOverflow** [comment]
Have you tried just using `from io import StringIO`, @Sechunt3r?

**Comment by Sicks3c** [comment]
@EdOverflow 
```python3 handler.py``` works fine but when I parse urls in the localhostm I get this error

```Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "handler.py", line 198, in post
    data = self.parseLinks(url, headers)
  File "handler.py", line 184, in parseLinks
    file = self.fetchURL(url, headers)
  File "handler.py", line 179, in fetchURL
    res = sc.execute(url)
  File "/opt/JSParser/safeurl.py", line 710, in execute
    response = StringIO.StringIO()
AttributeError: type object '_io.StringIO' has no attribute 'StringIO'
ERROR:tornado.access:500 POST /parse/ajax (::1) 73.78ms
```

**Comment by kunal812eee** [comment]
hey anyone can help me in these errors.
 ss attached

![Screenshot from 2019-08-06 18-13-08](https://user-images.githubusercontent.com/36692515/62540778-fa356b00-b875-11e9-82f3-52f734b77099.png)

**Comment by Sicks3c** [comment]
@kunal812eee replace ```import StringIO``` to ```from io import StringIO```

**Comment by pentestweb1337** [comment]
root@local:~/JSParser$ python3 handler.py
Traceback (most recent call last):
  File "handler.py", line 5, in <module>
    import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse, pycurl
ModuleNotFoundError: No module named 'urlparse'

**Comment by Guneetkaur03** [comment]
> Use the following:
> 
> ```python
> try:
>     from StringIO import StringIO
> except ImportError:
>     from io import StringIO
> ```

Thanks it worked

**Comment by undefined-rahulraj** [comment]
> @EdOverflow
> `python3 handler.py` works fine but when I parse urls in the localhostm I get this error
> 
> ```
>   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1590, in _execute
>     result = method(*self.path_args, **self.path_kwargs)
>   File "handler.py", line 198, in post
>     data = self.parseLinks(url, headers)
>   File "handler.py", line 184, in parseLinks
>     file = self.fetchURL(url, headers)
>   File "handler.py", line 179, in fetchURL
>     res = sc.execute(url)
>   File "/opt/JSParser/safeurl.py", line 710, in execute
>     response = StringIO.StringIO()
> AttributeError: type object '_io.StringIO' has no attribute 'StringIO'
> ERROR:tornado.access:500 POST /parse/ajax (::1) 73.78ms
> ```

Did you find any solution for this one ?

**Comment by sec000** [comment]
> > @EdOverflow
> > `python3 handler.py` works fine but when I parse urls in the localhostm I get this error
> > ```
> >   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1590, in _execute
> >     result = method(*self.path_args, **self.path_kwargs)
> >   File "handler.py", line 198, in post
> >     data = self.parseLinks(url, headers)
> >   File "handler.py", line 184, in parseLinks
> >     file = self.fetchURL(url, headers)
> >   File "handler.py", line 179, in fetchURL
> >     res = sc.execute(url)
> >   File "/opt/JSParser/safeurl.py", line 710, in execute
> >     response = StringIO.StringIO()
> > AttributeError: type object '_io.StringIO' has no attribute 'StringIO'
> > ERROR:tornado.access:500 POST /parse/ajax (::1) 73.78ms
> > ```
> 
> Did you find any solution for this one ?

Edit both files ( handler.py and safeurl.py)
from io import StringIO

**Comment by kahwekjrhkasdhfasg** [comment]
> > @EdOverflow
> > `python3 handler.py` works fine but when I parse urls in the localhostm I get this error
> > ```
> >   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1590, in _execute
> >     result = method(*self.path_args, **self.path_kwargs)
> >   File "handler.py", line 198, in post
> >     data = self.parseLinks(url, headers)
> >   File "handler.py", line 184, in parseLinks
> >     file = self.fetchURL(url, headers)
> >   File "handler.py", line 179, in fetchURL
> >     res = sc.execute(url)
> >   File "/opt/JSParser/safeurl.py", line 710, in execute
> >     response = StringIO.StringIO()
> > AttributeError: type object '_io.StringIO' has no attribute 'StringIO'
> > ERROR:tornado.access:500 POST /parse/ajax (::1) 73.78ms
> > ```
> 
> Did you find any solution for this one ?

In python 3.7, I edit safeurl.py  as following and it work
1. import io
2. edit line No.710 `response = StringIO.StringIO()` to `response = io.BytesIO()`
3. edit line No.732 `return response.getvalue()` to `return response.getvalue().decode('utf-8')`

**Comment by attacker34** [comment]
> Use the following:
> 
> ```python
> try:
>     from StringIO import StringIO
> except ImportError:
>     from io import StringIO
> ```

Hi @EdOverflow 
 Can You please let me know where to paste this snippet? 

Thanks.

**Comment by shikhayadav2481996** [comment]
> Have you tried just using `from io import StringIO`, @Sechunt3r?

I tried `from io import StringIO` this also then also I am getting error in installing StingIO and I am getting this error while installing StringIO ,
ERROR: Could not find a version that satisfies the requirement StringIO (from versions: none)
ERROR: No matching distribution found for StringIO

can any one help me in installing StingIO

**Comment by sailfish009** [comment]
you could use  StringIO, but most case  BytesIO is correct solution.

**Comment by ikish0re** [comment]
Traceback (most recent call last):
  File "handler.py", line 250, in <module>
    application.listen(portNum)
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use

Anyone help me to fix this error

Im getting this type of error

**Comment by zy9ard3** [comment]
> 
> 
> > Have you tried just using  `from io import StringIO`, @Sechunt3r ?
> 
> I tried `from io import StringIO` this also then also I am getting error in installing StingIO and I am getting this error while installing StringIO ,
> ERROR: Could not find a version that satisfies the requirement StringIO (from versions: none)
> ERROR: No matching distribution found for StringIO
> 
> can any one help me in installing StingIO

use pip3 install -r requirements.txt

**Comment by Crj777** [comment]
Edit safeurl.py and give
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
Then edit handler.py and in line 5 replace urlparse with urllib.parse
Then replace cgi with html  i.e 
from html import escape 
This will solve the issue thanks😊

**Comment by ShudarsanRegmi** [comment]
I got the following error: 
![image](https://user-images.githubusercontent.com/65646203/126886276-bb91f67a-12aa-406f-af90-2baa5e492fcc.png)

**Comment by TheRealXaiL** [comment]
@ShudarsanRegmi Literally what @Crj777 said. Replace "from cgi import escape" with "from html import scape"

**Comment by prabeshram** [comment]
while running python handler.py i get this issue

Traceback (most recent call last):
  File "/home/kalki/Desktop/bug_bounty/JSParser/handler.py", line 5, in <module>
    import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse, pycurl
  File "/home/kalki/Desktop/bug_bounty/JSParser/safeurl.py", line 18, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'

How can i fix this?

**Comment by weisisheng** [comment]
+1

**Comment by sushantvishu** [comment]
{{7*7}}

**Comment by sushantvishu** [comment]
<iframe+src=x+onload=prompt(1)>
