### ISSUE TITLE
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)

### ISSUE THREAD

**Issue by sawzeeyy** [nahamsec/JSParser#22]
Any help?

$ python3 handler.py
Traceback (most recent call last):
  File "handler.py", line 5, in <module>
    import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse
  File "/Users/../../JSParser/safeurl.py", line 17, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)

**Comment by Regala** [comment]
Assuming you're on macOS (High Sierra) check the following [link](https://cscheng.info/2018/01/26/installing-pycurl-on-macos-high-sierra.html) - worked for me.

Essentially:
`$ brew reinstall openssl`
`$ pip uninstall pycurl`
`$ pip install --install-option="--with-openssl" --install-option="--openssl-dir=/usr/local/opt/openssl" pycurl` 

I'm assuming you've ran setup.py before - if you do
`$ python handler.py`

Should work now.

**Comment by xhzeem** [comment]
Hi @Regala I can't uninsatall pycurl on my device I'm getting the error 
```
Cannot uninstall 'pycurl'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by attacker34** [comment]
> Hi @Regala I can't uninsatall pycurl on my device I'm getting the error
> 
> ```
> Cannot uninstall 'pycurl'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
> ```

Use 

sudo pip uninstall pycurl

**Comment by clirimemini** [comment]
For those who can't fix this on MacOS:
```
brew install pipenv
pipenv shell
export CPPFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib
pip install pycurl --global-option="--with-openssl"
```

**Comment by P1kAju** [comment]
Hi @sawzeeyy I'm pretty sure
![image](https://user-images.githubusercontent.com/25498052/69909994-e45c3f00-143e-11ea-9ae2-e4e86baeac8c.png)

**Comment by P1kAju** [comment]
Wow @sawzeeyy 
My hard change finally Successfully

- remove existing pycurl installation
pip3 uninstall pycurl

- export variable with your link-time ssl backend (which is openssl above)
export PYCURL_SSL_LIBRARY=openssl

- then, re-install pycurl with no cache
pip3 install pycurl --no-cache-dir


next question😂
![image](https://user-images.githubusercontent.com/25498052/69910050-b9261f80-143f-11ea-8d2d-478bea910ff5.png)

**Comment by FightingSuperYan** [comment]
if you use “pip install pycurl" in your anaconda virtulenvironment this problem may occur,i use "conda install pycurl",then this problem is solved

**Comment by chujiezheng** [comment]
> if you use “pip install pycurl" in your anaconda virtulenvironment this problem may occur,i use "conda install pycurl",then this problem is solved

Wonderful! Problem solved.
