### ISSUE TITLE
 Type object '_io.StringIO' has no attribute 'StringIO'

### ISSUE THREAD

**Issue by Muhammad-Qasim-Munir** [nahamsec/JSParser#29]
**Hi, Any Solution for the below error?**

```
ERROR:tornado.application:Uncaught exception POST /parse/ajax (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8008', method='POST', uri='/parse/ajax', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/Local/.local/share/virtualenvs/JSParser-yC77UK_z/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "handler.py", line 197, in post
    data = self.parseLinks(url, headers)
  File "handler.py", line 183, in parseLinks
    file = self.fetchURL(url, headers)
  File "handler.py", line 178, in fetchURL
    res = sc.execute(url)
  File "/Users/Local/Downloads/JSParser/safeurl.py", line 713, in execute
    response = StringIO.StringIO()
AttributeError: type object '_io.StringIO' has no attribute 'StringIO'
ERROR:tornado.access:500 POST /parse/ajax (127.0.0.1) 118.48ms

```

**Comment by JuWeber99** [comment]
i fixed it for me i think. should i open a pull request?

**Comment by JuWeber99** [comment]
but i dont think i have permissions... sorry if i am wrong... since i am new in contributing

**Comment by An0nym0us1337** [comment]
Ok

**Comment by JuWeber99** [comment]
Will there be any answer or information soon? or is this project deprecated now?

**Comment by D0N-B0T** [comment]
i have the same problem, i think op cant fix it.

**Comment by ghost** [comment]
Hey there use only Python 2.7 to run handler.py
It turned out fine after a long struggle for me
Uninstall tornado and install pip install tornado==5.1.1
