### ISSUE TITLE
ModuleNotFoundError: No module named 'StringIO'

### ISSUE THREAD

**Issue by ghost** [nahamsec/JSParser#31]
python3 handler.py 

Traceback (most recent call last):
  File "handler.py", line 5, in <module>
    import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse, pycurl
  File "/root/JSParser/safeurl.py", line 18, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'

was hoping someone has found a fix for this issue

**Comment by masoodbinmohammad** [comment]
Yes..I do have the same issue.. whats wrong with safeurl ?

**Comment by m4ll0k** [comment]
@soupnatzi change line 18 with `from io import StringIO`

**Comment by sushantdhopat** [comment]
where line18

**Comment by sushantdhopat** [comment]
i install it using this command"pip3 install StringIO"  give the error not version satisfyy
