### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by HolyBugx** [nahamsec/JSParser#40]
Hi , here are the steps i tried to install this : 
1- cloned the repo
2- python2 setup.py install
3- pip2 install -r requirements.txt
4- pip2 uninstall tornado
5- pip3 uninstall tornado
6- pip2 install tornado=5.1.1
7- pip3 install tornado=5.1.1
8- python2 handler.py

Traceback (most recent call last):
  File "handler.py", line 2, in <module>
    import tornado.ioloop, tornado.web, tornado.autoreload
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.1b1-py2.7-linux-x86_64.egg/tornado/ioloop.py", line 67
    def fileno(self) -> int:
                            ^
SyntaxError: invalid syntax

( the arrow is under "->" )

**Comment by HolyBugx** [comment]
Ok I Solved it , Steps : 

1- cd /usr/local/lib/python2.7/dist-packages
2- rm -rf torna*
3- python2 -m pip install tornado==5.1
4- python2 handler.py
