### ISSUE TITLE
zipp error in JSparser

### ISSUE THREAD

**Issue by Splint3r7** [nahamsec/JSParser#42]
`$ python2 handler.py`

Error: 

```
Traceback (most recent call last):
  File "handler.py", line 5, in <module>
    import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse, pycurl
  File "/home/hassankhan/tools/JSParser/safeurl.py", line 16, in <module>
    import netaddr
  File "/usr/local/lib/python2.7/dist-packages/netaddr-0.8.0-py2.7.egg/netaddr/__init__.py", line 18, in <module>
    from netaddr.core import (AddrConversionError, AddrFormatError,
  File "/usr/local/lib/python2.7/dist-packages/netaddr-0.8.0-py2.7.egg/netaddr/core.py", line 11, in <module>
    from netaddr.compat import _callable, _iter_dict_keys
  File "/usr/local/lib/python2.7/dist-packages/netaddr-0.8.0-py2.7.egg/netaddr/compat.py", line 93, in <module>
    import importlib_resources as _importlib_resources
  File "/usr/local/lib/python2.7/dist-packages/importlib_resources-3.3.0-py2.7.egg/importlib_resources/__init__.py", line 5, in <module>
    from ._common import (
  File "/usr/local/lib/python2.7/dist-packages/importlib_resources-3.3.0-py2.7.egg/importlib_resources/_common.py", line 9, in <module>
    from ._compat import (
  File "/usr/local/lib/python2.7/dist-packages/importlib_resources-3.3.0-py2.7.egg/importlib_resources/_compat.py", line 48, in <module>
    from zipp import Path as ZipPath  # type: ignore
  File "/usr/local/lib/python2.7/dist-packages/zipp-3.4.0-py2.7.egg/zipp.py", line 240
    def open(self, mode='r', *args, pwd=None, **kwargs):
                                      ^
SyntaxError: invalid syntax

```

**Comment by Splint3r7** [comment]
Solution:

1- Uninstall currently installed zip versions:

```
pip uninstall zipp==1.2.0
pip install zip
pip2 uninstall zipp
```

2- Install again

```
pip2 install zipp
```

Do follow the same for pycurl and install with pip2.

**Comment by Splint3r7** [comment]
Just posted a solution if anyone needed it. Closing the issue!
