### ISSUE TITLE
Error execution handler.py

### ISSUE THREAD

**Issue by tXambe** [nahamsec/JSParser#43]
Hello,

When I execute handler I have this error:

```
ImportError: /root/.cache/Python-Eggs/pycurl-7.43.0.6-py2.7-linux-x86_64.egg-tmp/pycurl.so: undefined symbol: PyUnicode_DecodeLocale

```

Any recomendation ?

A greeting and thanks

**Comment by ghost** [comment]
use this 
$ pip uninstall pycurl
$ pip install --install-option="--with-openssl" --install-option="--openssl-dir=/usr/local/opt/openssl" pycurl
$ python3 handler.py

**Comment by sumit554** [comment]
Traceback (most recent call last):
  File "/root/tools/JSParser/handler.py", line 5, in <module>
    import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse, pycurl
  File "/root/tools/JSParser/safeurl.py", line 18, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'



pls help me to solve this issue bro
