### ISSUE TITLE
No module named 'StringIO'

### ISSUE THREAD

**Issue by sumit554** [nahamsec/JSParser#56]
Traceback (most recent call last):
  File "/root/tools/JSParser/handler.py", line 5, in <module>
    import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse, pycurl
  File "/root/tools/JSParser/safeurl.py", line 18, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'

Pls help me to solve this issues

**Comment by ghost** [comment]
replace ````import StringIO```` to ``from io import StringIO``

**Comment by sumit554** [comment]
after replacing 

Traceback (most recent call last):
  File "/root/tools/JSParser/handler.py", line 5, in <module>
    import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse, pycurl
ModuleNotFoundError: No module named 'urlparse'

**Comment by sumit554** [comment]
already present urlparse handler.py

**Comment by kpomeroy1979** [comment]
I get the exact same error when trying ghosts suggestion.

**Comment by shishirS4** [comment]
replace import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse, pycurl, StringIO
 to  on handler.py file

to below one

import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, pycurl
from urllib.parse import urlparse
from io import StringIO
