### ISSUE TITLE
JS Parser error in handler.py

### ISSUE THREAD

**Issue by katravath15** [nahamsec/JSParser#59]
Shivas-MacBook-Pro:JSParser shivakatravath$ python3 handler.py 
Traceback (most recent call last):
  File "/Users/shivakatravath/recon/JSParser/handler.py", line 5, in <module>
    import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse, pycurl
  File "/Users/shivakatravath/recon/JSParser/safeurl.py", line 17, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)

**Comment by d0rksh** [comment]
finally made them to work :)
