### ISSUE TITLE
jsparser installation problem

### ISSUE THREAD

**Issue by prabeshram** [nahamsec/JSParser#61]
python handler.py              
Traceback (most recent call last):
  File "/home/kalki/Desktop/bug_bounty/JSParser/handler.py", line 5, in <module>
    import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse, pycurl
  File "/home/kalki/Desktop/bug_bounty/JSParser/safeurl.py", line 18, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'

please help me fix this problem

**Comment by prabeshram** [comment]
python handler.py
Traceback (most recent call last):
File "/home/kalki/Desktop/bug_bounty/JSParser/handler.py", line 5, in
import safeurl, types, sys, re, mimetypes, glob, jsbeautifier, urlparse, pycurl
File "/home/kalki/Desktop/bug_bounty/JSParser/safeurl.py", line 18, in
import StringIO
ModuleNotFoundError: No module named 'StringIO'

please, Can anyone help me on how to fix this issue?

**Comment by kpomeroy1979** [comment]
I get the same error. Not sure what the fix is but it seems like the author has no intentions of helping troubleshoot.

**Comment by kpomeroy1979** [comment]
This is the solution. Works 100% confirmed on Kali Linux

https://github.com/nahamsec/JSParser/issues/55

1. Download docker: https://www.docker.com/products/docker-desktop
2. In terminal (CMD): docker pull andmyhacks/jsparser
3. In terminal (CMD): docker run -p 8008:8008 andmyhacks/jsparser
Access: http://127.0.0.1:8008/

**Comment by shishirS4** [comment]
Some changes on safeurl.py file 

like remove the import StringIO

to 

from io import StringIO

**Comment by RazorBest** [comment]
I made a fork that supports Python3. The issue should be solved there: https://github.com/RazorBest/JSParser3
